<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
  <Compile Remove="furi-source-code/**/*.cs;tests/**/*.cs" />
  <Reference Include="BepInEx">
    <HintPath>lib/BepInEx.dll</HintPath>
  </Reference>
  <Reference Include="0Harmony">
    <HintPath>lib/0Harmony.dll</HintPath>
  </Reference>
  <Reference Include="Assembly-CSharp">
    <HintPath>lib/Assembly-CSharp.dll</HintPath>
  </Reference>
  <Reference Include="UnityEngine">
    <HintPath>lib/UnityEngine.dll</HintPath>
  </Reference>
  <Reference Include="UnityEngine.CoreModule">
    <HintPath>lib/UnityEngine.CoreModule.dll</HintPath>
  </Reference>
  <Reference Include="UnityEngine.UI">
    <HintPath>lib/UnityEngine.UI.dll</HintPath>
  </Reference>
</ItemGroup>

</Project>
